# Generated by Django 5.1.7 on 2025-03-19 14:13

import location.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=location.models.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('image_hash', 'home_address')},
            },
        ),
    ]
