# Generated by Django 5.1.7 on 2025-03-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='locationimage',
            name='landmark',
        ),
    ]
