# Generated by Django 5.1.6 on 2025-03-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_productimage_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='LocationImage',
        ),
    ]
