# Generated by Django 5.1.6 on 2025-03-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_rename_productimage_locationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
