# Generated by Django 5.1.7 on 2025-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_locationimage_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationimage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationimage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
