# Generated by Django 5.1.7 on 2025-03-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_locationimage_distance_km_locationimage_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
