# Generated by Django 5.1.7 on 2025-03-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_locationimage_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
