# Generated by Django 5.1.7 on 2025-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_locationimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
